### ISSUE TITLE
Jitteryness simple fix

### ISSUE THREAD

**Issue by kestasjk** [martindevans/MumbleSharp#46]
Hi, we're using this in a new application and the jitter was quite an issue, but I found (by accident) that if I paused the application for a moment then continued everything would be fine.

After playing around with AudioBuffer.cs to try and make it buffer more data without luck I found that if AudioBuffer detects when Read() isn't returning enough info it should just set a flag "IsJitterring", which can be made accessible via the MumbleSharp Model/User.cs class.

Then the EncodedVoiceDelegate looks for user.IsJittering , and if so it pauses the user, turns the jitter flag off, and saves the current time. Then once it has been, say, 100-200 ms since the pause started the user is unpaused and the voice is smooth again. I am testing this out now but it seems pretty robust.

**Comment by martindevans** [comment]
What you're describing there is essentially a dynamic jitter buffer - as network conditions worsen you deliberately delay the audio so that there's more of a buffer between playback and the bad network conditions. Usually this is done by measuring the arrival time of packets (which should be constant), calculating jitter from that and delaying playback accordingly. Really advanced jitter buffers will even _strentch_ or _squeeze_ samples as they're playing back to grow or shrink the buffer in accordance with real-time jitter measurements!

Would you be willing to put in a PR which delays the playback of _all_ voice by a small fixed amount (say 50ms) and making that delay configurable? We can then come back later (or you can in a followup PR if you like) and add something that measures network jitter and sets the delay.

**Comment by kestasjk** [comment]
I actually didn't have much luck adding a static delay. What I'll probably do is fork and commit all changes to the fork, then you can pick and choose what you want or decide to do things differently. What I commit will (eventually) be a production PTT system used over wifi so it should at least give something to compare to.

**Comment by trevorirwin** [comment]
I've made some progress on this, see #52 for details!

**Comment by dextercai** [comment]
Can this problem be fixed by referring to "BananaHemic/Mumble-Unity"?
